name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: Azure
    steps:
      - uses: actions/checkout@main
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          scope: subscription
          region: westeurope
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./main.bicep
          parameters: prefix=rr location=westeurope mscid=${{ secrets.MSCID }} token=${{ secrets.GH_PAT }} deploymentOperatorId=${{ secrets.DEPLOYMENT_OPERATOR_ID }}
          failOnStdErr: false
