on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          scope: subscription
          region: westeurope
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./main.bicep
          parameters: prefix=rr location=westeurope 
          # parameters: prefix=rr location=westeurope token=${{ secrets.GH_PAT }}
          failOnStdErr: false
